---
- hosts: db
  tasks:
    - name: Include Secrets
      include_vars: secret.yml

      # Solved: Giving the ansible root-privlege solved error
    - name: Copy MariaDB to /etc/yum.repos.d 
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

      #Solved: Changed to a list of service name. Using yum (for Centos) instead of apt (for Ubuntu)
    - name: Update MariaDB services
      become: yes
      yum: name={{ item }} update_cache=yes state=present
      with_items:
        - MariaDB-client

      #Solved: Missing permissions to execute
    - name: Unpacking db.tgz and setting permissions 
      unarchive: src=db/db.tgz dest=~/ mode=0777

      #Gives no error for first run, but gives gives permission error for root for every following runs but ignores error
    - name: Create databases with script make_databases.
      command: ./make_databases.sh {{ db_password }} tf-20161119064332410429724lkp.cta3tvlj13sn.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
