---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    db_host: tf-20161120202536694408029u7e.cta3tvlj13sn.us-west-2.rds.amazonaws.com:3306
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: Include Secrets
      include_vars: secret.yml

      #Solved: Changed to root (become)
    - name: Update epel-release
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: Install PHP 5.4
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: Update multiple php services
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install

      #Solved Warning: split up to get_url and shell
    - name: Download installer
      become: yes
      get_url: 
        url: https://getcomposer.org/installer
        dest: /usr/local/bin/composer
        mode: 0777

      #Solved Warning: split up to get_url and shell
    - name: Install composer
      become: yes
      shell: php /usr/local/bin/composer --install-dir=/usr/local/bin --filename=composer

    - name: Copy nginx to /etc/nginx/nginx.conf
      become: yes
      copy: src=web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name: Render vhost.conf template to server
      become: yes
      template: src=web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

      #Solved: Change to root (become)
    - name: Render php.ini template to server
      become: yes
      template: src=web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: Copy php-fpm-web.conf to /etc/php-fpm.d/
      become: yes
      copy: src=web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: Restart nginx and start on boot when conditions match
      become: yes
      systemd: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

      #Solved: Change to root (become)
    - name: Restart php-fdm and start on boot when conditions match
      become: yes
      systemd: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

      #Solved: Change state to Directory
    - name: Create directories if not exists
      become: yes
      file: path="{{ service_dir }}" state=directory

    - name: Unpack curriculum
      become: yes
      unarchive: src=web/{{ service_name }}.tgz dest="{{ service_dir }}" mode=0755

    - name: Update composer
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}

      #Solved Warning: Changed to file-module
    - name: Change permission of all files and subdirectories
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777

      #Solved Warning: Changed to file-module
      #Solved: Change to root (become)
    - name: Change ownership of all files and subdirectories
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx

    - name: Render env.j2 template to server
      become: yes
      template: src=web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx

